### ISSUE TITLE
Full Implementation Code?

### ISSUE THREAD

**Issue by SangRyul** [JohnLaMaster/dropCluster#1]
I just wondered that there are fully implemented code with dropCluster. I want to use it at my work, but I don't know how to start

**Comment by JohnLaMaster** [comment]
Hi @SangRyul, I have not yet published a ResNet model with dropCluster. Depending on how my current manuscript submission goes, that may happen in the next few months. If so, I can let you know. The readme for this repo has the code and a brief explanation for implementing it. According to the original paper, dropCluster is added only at the end of the convolutional stem, i.e. before layer0 of the official resnet code. Just import the module according to the dimensionality of your data. (1d signals vs 2d images vs 3d volumes) I also have code snippets to add to your training script. The scheduler is used to update the dropout rate (it scales linearly from 0 to p) as training progresses. Additionally, you will have to determine, based on trial runs, which epoch to activate dropCluster. My models reach a stable feature representation before 40 epochs, so I activate it earlier. I also update the segmentations every 10 epochs instead of only twice. Maybe it's not necessary, but it's not that much overhead for me and it ensures that the cluster maps stay accurate. These hyperparameters are the options listed in the top half of the training snippet.
As a heads up, if you get a CUDA error in the epoch you activate this module, it could be the batch size is too large for the segmentation to run on the GPU. You can run the segmentation on the CPU if necessary. Otherwise, you may have to get creative to make it all fit in the RAM you have available.
Side note: My implementation does not use the same segmentation algorithm as the original paper. This implementation was unavailable and not easily implemented. Therefore, I used a similar feature aglomeration algorithm.

**Comment by SangRyul** [comment]
Thanks a lot :) and thank you for your project
